package ProyectoSistemaEscolar.dsoo.presentacion.login;

/**
 *
 * @author alber
 */

import ProyectoSistemaEscolar.dsoo.presentacion.alumnos.*;
import ProyectoSistemaEscolar.dsoo.presentacion.profesores.*;
import ProyectoSistemaEscolar.dsoo.presentacion.grupos.*;
import ProyectoSistemaEscolar.dsoo.presentacion.calificaciones.*;
import ProyectoSistemaEscolar.dsoo.presentacion.materias.*;
import java.awt.Window;
public class Principal_admin extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public Principal_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        alumnosBtn = new javax.swing.JButton();
        profesoresBtn = new javax.swing.JButton();
        calificacionesBtn = new javax.swing.JButton();
        gruposBtn = new javax.swing.JButton();
        materiaBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        text_ini = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(241, 250, 218));

        jPanel2.setBackground(new java.awt.Color(45, 149, 150));

        alumnosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Graduation Cap.png"))); // NOI18N
        alumnosBtn.setText("Alumnos");
        alumnosBtn.setToolTipText("");
        alumnosBtn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        alumnosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alumnosBtnActionPerformed(evt);
            }
        });

        profesoresBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pencil and pen.png"))); // NOI18N
        profesoresBtn.setText("Profesores");
        profesoresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesoresBtnActionPerformed(evt);
            }
        });

        calificacionesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Wirite.png"))); // NOI18N
        calificacionesBtn.setText("Calificaciones");
        calificacionesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calificacionesBtnActionPerformed(evt);
            }
        });

        gruposBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prueba.png"))); // NOI18N
        gruposBtn.setText("Grupos");
        gruposBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gruposBtnActionPerformed(evt);
            }
        });

        materiaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libros (1).png"))); // NOI18N
        materiaBtn.setText("Materias");
        materiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(alumnosBtn)
                .addGap(40, 40, 40)
                .addComponent(profesoresBtn)
                .addGap(40, 40, 40)
                .addComponent(calificacionesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(gruposBtn)
                .addGap(40, 40, 40)
                .addComponent(materiaBtn)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alumnosBtn)
                    .addComponent(profesoresBtn)
                    .addComponent(calificacionesBtn)
                    .addComponent(gruposBtn)
                    .addComponent(materiaBtn))
                .addGap(0, 37, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(38, 80, 115));

        text_ini.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        text_ini.setForeground(new java.awt.Color(255, 255, 255));
        text_ini.setText("Sistema Control Escolar");

        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login 1@2x.png"))); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text_ini)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_salir)
                .addGap(48, 48, 48))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_ini)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // Obtiene todas las ventanas abiertas
        Window[] ventanas = Window.getWindows();

        // Cierra cada ventana abierta
        for (Window ventana : ventanas) {
            ventana.dispose();
        }

        // Abre la siguiente ventana
        login log = new login();
        log.setVisible(true);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void alumnosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alumnosBtnActionPerformed
        Alumnos frameAlumno = new Alumnos();
        frameAlumno.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_alumnosBtnActionPerformed

    private void profesoresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesoresBtnActionPerformed
        Profesores frameProfesores = new Profesores();
        frameProfesores.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_profesoresBtnActionPerformed

    private void calificacionesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calificacionesBtnActionPerformed
        calificaciones frameCalificaciones = new calificaciones();
        frameCalificaciones.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_calificacionesBtnActionPerformed

    private void gruposBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gruposBtnActionPerformed
        Grupos frameGrupo = new Grupos();
        frameGrupo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_gruposBtnActionPerformed

    private void materiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaBtnActionPerformed
        Materias frameMateria = new Materias();
        frameMateria.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_materiaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alumnosBtn;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton calificacionesBtn;
    private javax.swing.JButton gruposBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton materiaBtn;
    private javax.swing.JButton profesoresBtn;
    private javax.swing.JLabel text_ini;
    // End of variables declaration//GEN-END:variables
}
