package ProyectoSistemaEscolar.dsoo.presentacion.materias;

/**
 *
 * @author alber
 */

import ProyectoSistemaEscolar.bd.domain.Alumno;
import ProyectoSistemaEscolar.bd.domain.Grupo;
import ProyectoSistemaEscolar.dsoo.presentacion.login.*;
import ProyectoSistemaEscolar.bd.domain.Materia;
import ProyectoSistemaEscolar.bd.domain.Profesor;
import ProyectoSistemaEscolar.dao.alumnos.AlumnoDaoImpl;
import ProyectoSistemaEscolar.dao.materias.*;
import ProyectoSistemaEscolar.dao.profesores.ProfesorDaoImpl;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
public class MateriasProfesor extends javax.swing.JFrame {
    private ArrayList<Materia> globalM = new ArrayList<>();
    private ArrayList<Profesor> profeGlobal = new ArrayList<>();
    
    private DefaultTableModel dtm;
    private Object[] fila = new Object[6];
    
    public void asignar(ArrayList<Materia> newM){
        globalM = newM;
        listar();
        listarCombo();
    }
    
    private void listarCombo(){
        
        for (Materia grupo : globalM) {
            materiaBox.addItem(grupo.getNombre());
            //System.out.println("id_grupo: "+grupo.getId_grupo()+", nombre: "+grupo.getNombre());
        }
    }
    
    private void listar(){
        dtm = (DefaultTableModel) profeTb.getModel();
        
        ProfesorDaoImpl profeService = new ProfesorDaoImpl();
        ArrayList<Profesor> profesores = profeService.listarProfesor();
        profeGlobal = profesores;
        for (Profesor profe : profesores) {
            fila[0] = profe.getNombres();
            fila[1] = profe.getApellido_paterno();
            fila[2] = profe.getApellido_materno();
            fila[3] = profe.getTelefono();
            fila[4] = profe.getCorreo();
            for (Materia mate : globalM) {
                if (mate.getId() == profe.getId_materia() ) {
                    fila[5] = mate.getNombre();
                }
            }
            //fila[5] = profe.getId_materia();
            dtm.addRow(fila);
        }
        //fila[5] = globalM.get(alumno.getId_grupo()).getNombre();
    }
    
    public void llamar(){
        for (int i = 0; i < profeTb.getRowCount(); i++) {
            dtm.removeRow(i);
            i-=1;
        }
        listar();
    }
    /**
     * Creates new form MateriasProfesor
     */
    public MateriasProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        enviarBtn = new javax.swing.JButton();
        materiaBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        profeTb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        enviarBtn.setBackground(new java.awt.Color(45, 149, 150));
        enviarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Check.png"))); // NOI18N
        enviarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarBtnActionPerformed(evt);
            }
        });

        materiaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materiaBoxActionPerformed(evt);
            }
        });

        profeTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre(s)", "Apellido paterno", "Apellido materno", "Teléfono", "Correo", "Materia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(profeTb);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(volver)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(materiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(enviarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volver)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(materiaBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(enviarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void materiaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materiaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materiaBoxActionPerformed

    private void enviarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarBtnActionPerformed
        try {
        int selectedRow = profeTb.getSelectedRow();
        
        if (selectedRow == -1) {
            throw new IndexOutOfBoundsException("No se ha seleccionado ninguna fila");
        }
        Profesor prof = profeGlobal.get(selectedRow);
        
        //System.out.println(gruposBox.getSelectedIndex());
        
        Materia gru = globalM.get(materiaBox.getSelectedIndex());
        
        prof.setId_materia(gru.getId());
        ProfesorDaoImpl profesorService = new ProfesorDaoImpl();
        
        //System.out.println("ID Grupo: " + prof.getId_materia());
        
        if(profesorService.asignarMateriaProfesor(prof)){
            JOptionPane.showMessageDialog(rootPane,"Materia Asignado");
            llamar();
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se pudo asignar");
        }
        /*System.out.println("ID Alumno: " + mat.getId_alumno());
        System.out.println("Nombre: " + mat.getNombre());
        System.out.println("Apellido Paterno: " + mat.getApellido_paterno());
        System.out.println("Apellido Materno: " + mat.getApellido_materno());
        System.out.println("Matrícula: " + mat.getMatricula());
        System.out.println("Correo: " + mat.getCorreo());
        System.out.println("Password: " + mat.getPassword());
        System.out.println("ID Grupo: " + mat.getId_grupo());*/
        
        } catch (IndexOutOfBoundsException e) {
            // Manejo de la excepción cuando no se selecciona ninguna fila
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enviarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriasProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriasProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriasProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriasProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MateriasProfesor().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enviarBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> materiaBox;
    private javax.swing.JTable profeTb;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
