package ProyectoSistemaEscolar.dsoo.presentacion.grupos;

import ProyectoSistemaEscolar.bd.domain.Alumno;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alber
 */
import ProyectoSistemaEscolar.bd.domain.Grupo;
import ProyectoSistemaEscolar.dao.alumnos.AlumnoDaoImpl;
import javax.swing.JOptionPane;
public class GruposAlumno extends javax.swing.JFrame {
    
    private ArrayList<Grupo> globalM = new ArrayList<>();
    private DefaultTableModel dtm;
    private Object[] fila = new Object[6];
    private ArrayList<Alumno> globalAlumno ;
    
    public void asignar(ArrayList<Grupo> newM){
        globalM = newM;
        listarTabla();
        listarCombo();
    }
    
    private void listarCombo(){
        
        for (Grupo grupo : globalM) {
            gruposBox.addItem(grupo.getNombre());
            //System.out.println("id_grupo: "+grupo.getId_grupo()+", nombre: "+grupo.getNombre());
        }
    }
    
    private void listarTabla(){
        dtm = (DefaultTableModel) alumnosTb.getModel();
        AlumnoDaoImpl alumnoService = new AlumnoDaoImpl();
        ArrayList<Alumno> alumnos = alumnoService.listarAlumno();
        globalAlumno = alumnos;
        for (Alumno alumno : alumnos) {
            
            fila[0] = alumno.getMatricula();
            fila[1] = alumno.getNombre();
            fila[2] = alumno.getApellido_paterno();
            fila[3] = alumno.getApellido_materno();
            fila[4] = alumno.getCorreo();
            //Materia mat = globalM.get(0);
            for (Grupo grupo : globalM) {
                if (grupo.getId_grupo()== alumno.getId_grupo()) {
                    fila[5] = grupo.getNombre();
                }
            }
            
            //fila[5] = mat.getNombre();
            dtm.addRow(fila);
        }
    }
    
    public void llamar(){
        for (int i = 0; i < alumnosTb.getRowCount(); i++) {
            dtm.removeRow(i);
            i-=1;
        }
        listarTabla();
    }
    /**
     * Creates new form GruposAlumno
     */
    public GruposAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        enviarBtn = new javax.swing.JButton();
        gruposBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        alumnosTb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        enviarBtn.setBackground(new java.awt.Color(45, 149, 150));
        enviarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Check.png"))); // NOI18N
        enviarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarBtnActionPerformed(evt);
            }
        });

        gruposBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gruposBoxActionPerformed(evt);
            }
        });

        alumnosTb.setForeground(new java.awt.Color(38, 80, 115));
        alumnosTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nombre", "Apellido Paterno", "Apellido Materno", "Correo", "Grupo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(alumnosTb);

        jLabel1.setText("Listado de Alumnos con su Grupo");

        jLabel2.setText("Seleccione un nuevo Grupo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(volver)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gruposBox, 0, 245, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(enviarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(gruposBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(enviarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void enviarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarBtnActionPerformed
        //System.out.println(alumnosTb.getSelectedRow());
        
        try {
        int selectedRow = alumnosTb.getSelectedRow();
        
        if (selectedRow == -1) {
            throw new IndexOutOfBoundsException("No se ha seleccionado ninguna fila");
        }
        Alumno mat = globalAlumno.get(selectedRow);
        
        //System.out.println(gruposBox.getSelectedIndex());
        
        Grupo gru = globalM.get(gruposBox.getSelectedIndex());
        
        mat.setId_grupo(gru.getId_grupo());
        AlumnoDaoImpl alumnoService = new AlumnoDaoImpl();
        
        
        
        if(alumnoService.asignarGrupoAlumno(mat)){
            JOptionPane.showMessageDialog(rootPane,"Grupo Asignado");
            llamar();
        }else{
            JOptionPane.showMessageDialog(rootPane, "No se pudo asignar");
        }
        /*System.out.println("ID Alumno: " + mat.getId_alumno());
        System.out.println("Nombre: " + mat.getNombre());
        System.out.println("Apellido Paterno: " + mat.getApellido_paterno());
        System.out.println("Apellido Materno: " + mat.getApellido_materno());
        System.out.println("Matrícula: " + mat.getMatricula());
        System.out.println("Correo: " + mat.getCorreo());
        System.out.println("Password: " + mat.getPassword());
        System.out.println("ID Grupo: " + mat.getId_grupo());*/
        
        } catch (IndexOutOfBoundsException e) {
            // Manejo de la excepción cuando no se selecciona ninguna fila
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_enviarBtnActionPerformed

    private void gruposBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gruposBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gruposBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GruposAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GruposAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GruposAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GruposAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GruposAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alumnosTb;
    private javax.swing.JButton enviarBtn;
    private javax.swing.JComboBox<String> gruposBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
