package ProyectoSistemaEscolar.dsoo.presentacion.calificaciones;

/**
 *
 * @author alber
 */
import ProyectoSistemaEscolar.bd.domain.Alumno;
import ProyectoSistemaEscolar.bd.domain.Calificacion;
import ProyectoSistemaEscolar.bd.domain.Grupo;
import ProyectoSistemaEscolar.dao.alumnos.*;
import ProyectoSistemaEscolar.dao.calificacion.CalificacionDaoImpl;
import ProyectoSistemaEscolar.dsoo.presentacion.login.*;
import java.util.ArrayList;
import ProyectoSistemaEscolar.dao.grupos.*;
import ProyectoSistemaEscolar.dao.union.UnionDaoImpl;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class calificaciones extends javax.swing.JFrame {
    private int idG = -1;
    private DefaultTableModel dtm;
    private Object[] fila = new Object[10];
    /**
     * Creates new form calificaciones
     */
    private void listar(){
        AlumnoDaoImpl alumnoService = new AlumnoDaoImpl();
        ArrayList<Alumno> alumnos = alumnoService.listarAlumno();
        for (Alumno alumno : alumnos) {
            //alumnosBox.addItem(alumno.getNombre());
        }
        GrupoDaoImpl instance = new GrupoDaoImpl();
        ArrayList<Grupo> grupos = instance.listarGrupo();
        for (Grupo grupo : grupos) {
            //gruposBox.addItem(grupo.getNombre());
            //System.out.println("id_grupo: "+grupo.getId_grupo()+", nombre: "+grupo.getNombre());
        }
        dtm = (DefaultTableModel) califTb.getModel();
        
        UnionDaoImpl unionService = new UnionDaoImpl();
        CalificacionDaoImpl calif = new CalificacionDaoImpl();
        ArrayList<ArrayList<String>> dobleArrayList = unionService.listarMateriasTodo();
        for (ArrayList<String> lista : dobleArrayList) {
            int i = 0;
            for (String elemento : lista) {
                fila[i] = elemento;
                if(i==4){
                    i++;
                    //System.out.println("entramos");
                    Calificacion ca = calif.listarCalificacionesId(Integer.parseInt(elemento));
                    fila[i] = ca.getParcial1();
                    i++;
                    fila[i] = ca.getParcial2();
                    i++;
                    fila[i] = ca.getParcial3();
                    i++;
                    fila[i] = ca.getOrdinario();
                    i++;
                    fila[i] = ca.getExtra1();
                }
                i++;
            }
            dtm.addRow(fila);
        }
    }
    
        
    public void llamar() {
        for (int i = 0; i < califTb.getRowCount(); i++) {
            dtm.removeRow(i);
            i--;
        }
        listar();
        //listarCombo();
    }
    
    public calificaciones() {
        initComponents();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        enviarBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        califTb = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        asignarMaGBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        parcialTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        parcial2Txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        parcial3Txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ordinarioTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        extraTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        enviarBtn.setBackground(new java.awt.Color(0, 153, 0));
        enviarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Check.png"))); // NOI18N
        enviarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarBtnActionPerformed(evt);
            }
        });

        califTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Materia", "Alumno", "Grupo", "Id_Calificacion", "Parcial 1", "Parcial 2", "Parcial 3", "Ordinario", "Extra"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(califTb);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Visualizacion de calificaciones");

        asignarMaGBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/asignacion.png"))); // NOI18N
        asignarMaGBtn.setText("Asignar Materias a Grupo");
        asignarMaGBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarMaGBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Guardar Cambios");

        jLabel2.setText("Parcial 1");

        jLabel3.setText("Parcial 2");

        jLabel4.setText("Parcial 3");

        jLabel6.setText("Ordinario");

        jLabel7.setText("Extra");

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(volver)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asignarMaGBtn)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(enviarBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(parcialTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(parcial2Txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(parcial3Txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ordinarioTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(extraTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volver)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(asignarMaGBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parcialTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parcial2Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parcial3Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordinarioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(extraTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enviarBtn)))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        Principal_admin ventanaPrincipal = new Principal_admin();
        ventanaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void enviarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarBtnActionPerformed
            if(idG != -1){
            CalificacionDaoImpl instance = new CalificacionDaoImpl();
            Calificacion datoModifi = new Calificacion();
            
            
            try {
                // Intenta convertir el texto a entero
                int parcial = Integer.parseInt(parcialTxt.getText());
                if(parcial > 10)
                    throw new NumberFormatException("Excedido");
                
                int parcial2 = Integer.parseInt(parcial2Txt.getText());
                if(parcial2 > 10)
                    throw new NumberFormatException("Excedido");
                
                int parcial3 = Integer.parseInt(parcial3Txt.getText());
                if(parcial3 > 10)
                    throw new NumberFormatException("Excedido");
                
                int ordinario = Integer.parseInt(ordinarioTxt.getText());
                if(ordinario > 10)
                    throw new NumberFormatException("Excedido");
                
                int extra = Integer.parseInt(extraTxt.getText());
                if(extra > 10)
                    throw new NumberFormatException("Excedido");
                
                datoModifi.setIdCalificacion(idG);
                datoModifi.setParcial1(parcial);
                datoModifi.setParcial2(parcial2);
                datoModifi.setParcial3(parcial3);
                datoModifi.setOrdinario(ordinario);
                datoModifi.setExtra1(extra);
                
                if(instance.modificarCalificacion(datoModifi))
                    JOptionPane.showMessageDialog(rootPane,"Modificado");
                else
                    JOptionPane.showMessageDialog(rootPane,"No se pudo modificar");
                idG = -1;
                parcialTxt.setText("");
                parcial2Txt.setText("");
                parcial3Txt.setText("");
                ordinarioTxt.setText("");
                extraTxt.setText("");
                llamar();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "No se permiten numeros con decimales o mayores a 10.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane,"Seleccione un alumno para modificar");
        }
    }//GEN-LAST:event_enviarBtnActionPerformed

    private void asignarMaGBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarMaGBtnActionPerformed
        calificacionesModal frameMateriaP = new calificacionesModal();
        frameMateriaP.asignar(this);
        frameMateriaP.setVisible(true);
    }//GEN-LAST:event_asignarMaGBtnActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        try {
            int fila_sel = califTb.getSelectedRow();
            
            if (fila_sel == -1) {
                throw new IndexOutOfBoundsException("No se ha seleccionado ninguna fila");
            }
            //System.out.println( dtm.getValueAt(fila_sel, 4));
            idG = Integer.parseInt(dtm.getValueAt(fila_sel, 4).toString());
            parcialTxt.setText(dtm.getValueAt(fila_sel, 5).toString());
            parcial2Txt.setText(dtm.getValueAt(fila_sel, 6).toString());
            parcial3Txt.setText(dtm.getValueAt(fila_sel, 7).toString());
            ordinarioTxt.setText(dtm.getValueAt(fila_sel, 8).toString());
            extraTxt.setText(dtm.getValueAt(fila_sel, 9).toString());

        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar primero un profesor de la tabla.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new calificaciones().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asignarMaGBtn;
    private javax.swing.JTable califTb;
    private javax.swing.JButton editar;
    private javax.swing.JButton enviarBtn;
    private javax.swing.JTextField extraTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ordinarioTxt;
    private javax.swing.JTextField parcial2Txt;
    private javax.swing.JTextField parcial3Txt;
    private javax.swing.JTextField parcialTxt;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
